-- Runs automatically the first time the postgres container initialises an empty
-- data directory (mounted into /docker-entrypoint-initdb.d). Mirrors the schema
-- the Kafka consumer (pipeline/kafka_consumer.py) inserts into.
CREATE TABLE IF NOT EXISTS sensor_events (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts         timestamptz NOT NULL,
    device_id  text,
    sensor     text,
    metric     text,
    value      double precision,
    unit       text,
    topic      text,
    event_type text,
    source     text
);
